export enum CategoryIcon {
	SHOPPING = 'shopping_cart',
	RESTAURANT = 'restaurant',
	FOOD = 'fastfood',
	CAR = 'directions_car',
	GAS = 'local_gas_station',
	GIFT = 'card_giftcard',
	PLANE = 'flight',
	STAY = 'hotel',
	MOVIE = 'movie',
	DRINK = 'local_bar',
	PARKING = 'local_parking',
	TAXI = 'local_taxi',
	GOLF = 'golf_course',
}
