version: "3.8"
services:
  mikane_test_db:
    image: postgres:15
    container_name: mikane_test_db
    ports:
      - "37000:5432"
    environment:
      - ENVIRONMENT=test
      - POSTGRES_DB=mikanetest
      - POSTGRES_USER=mikane_testuser
      - POSTGRES_PASSWORD=MikaneTestPassword!123
      - DB_HOST=localhost
      - DB_USER=mikane_testuser
      - DB_PASSWORD=MikaneTestPassword!123
    volumes:
      - ../bash_scripts/db_init.sh:/docker-entrypoint-initdb.d/db_init.sh
      - ../bash_scripts:/bash_scripts
      - ../db_scripts:/db_scripts
