version: "3.8"
# name: mikane
services:
  server:
    build:
      context: ./
      args:
        SERVER_URL: 
        SERVER_DESCRIPTION: 
    image: mikane:latest
    container_name: api
    ports:
      - "3002:3002"
    env_file:
      - .env
    restart: unless-stopped
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db
    user: root
    ports:
      - "1433:1433"
    env_file:
      - .env
    environment:
      - ACCEPT_EULA=Y
    command: /bin/bash ./entrypoint.sh
    volumes:
      - ./db_data:/var/opt/mssql/data
      - ./entrypoint.sh:/entrypoint.sh
      - ./db_scripts:/db_scripts
    restart: unless-stopped
