version: "3.8"
services:
  server:
    build:
      context: ./
      args:
        SERVER_URL: 
        SERVER_DESCRIPTION: 
    image: mikane:latest
    container_name: api
    ports:
      - "3002:3002"
    env_file:
      - .env
    restart: unless-stopped
  db:
    image: postgres:15
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=mikane
      - DB_HOST=localhost
    volumes:
      - ./pg_db_data:/var/lib/postgresql/data
      - ./bash_scripts/db_init.sh:/docker-entrypoint-initdb.d/db_init.sh
      - ./bash_scripts:/bash_scripts
      - ./db_scripts:/db_scripts
    restart: unless-stopped
