version: "3.8"
services:
  server:
      depends_on:
        - db
      build: ./
      ports:
        - "5000:5000"
      env_file:
        - .env
      command: /bin/bash ./entrypoint.sh
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    env_file:
      - .env
    environment:
      - ACCEPT_EULA=Y
