version: "3.8"
services:
  server:
      depends_on:
        - db
      build: ./
      ports:
        - "5000:5000"
      env_file:
        - .env
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    env_file:
      - .env
    environment:
      - ACCEPT_EULA=Y
    command: /bin/bash ./entrypoint.sh
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./db_scripts/:/db_scripts/
      - ./db_data:/var/opt/mssql/data
