name: api-staging

on:
  push:
    branches: [ "develop" ]

env:
  NODE_VERSION: 18.16.1

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./server/

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: ./server/package-lock.json

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2.5.1
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Install dependencies
      run: npm ci

    - name: Create build
      run: npm run build

    - name: Deploy with rsync
      run: rsync --dry-run -avz ./build/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/opt/mikane-staging/
