name: api

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  NODE_VERSION: 18.16.1

jobs:

  build:
    runs-on: ubuntu-latest
        
    defaults:
      run:
        working-directory: ./server/

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ./server/package-lock.json
          
      - name: Install dependencies
        run: npm ci

      - name: Create build
        run: npm run build

  test:
    runs-on: ubuntu-latest
    
    env:
      DB_HOST: localhost
      DB_PORT: 1433
      DB_DATABASE: mikane
      DB_USER: SA
      DB_PASSWORD: MikaneTestPassword!123

    # services:
    #   db:
    #     image: mcr.microsoft.com/mssql/server:2022-latest
    #     env:
    #       MSSQL_SA_PASSWORD: "${{ env.DB_PASSWORD }}"
    #       ACCEPT_EULA: 'Y'
    #     ports:
    #       - 1433:1433
    #     volumes:
    #       - /server/bash_scripts:/bash_scripts
    #       - /server/db_scripts:/db_scripts
    #     options: >-
    #       --name mssqldb

    defaults:
      run:
        working-directory: ./server/

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ./server/package-lock.json
      
      - name: Create DB
        run: |
          docker run -d \
          --name mssqldb \
          -e MSSQL_SA_PASSWORD="${{ env.DB_PASSWORD }}" \
          -e ACCEPT_EULA=Y \
          -p "${{ env.DB_PORT }}":1433 \
          -v ${{ github.workspace }}/server/bash_scripts:/bash_scripts \
          -v ${{ github.workspace }}/server/db_scripts:/db_scripts \
          mcr.microsoft.com/mssql/server:2022-latest

      - name: Run db_init
        run: |
          chmod -R +x ./bash_scripts
          docker exec \
          -e DB_HOST="${{ env.DB_HOST }}" \
          -e DB_PORT=1433 \
          -e DB_USER="${{ env.DB_USER }}" \
          -e DB_PASSWORD="${{ env.DB_PASSWORD }}" \
          mssqldb /bin/bash ./bash_scripts/db_init.sh

      - name: Install dependencies
        run: npm ci

      - name: Install sqlcmd
        run: |
          sudo apt-get update
          sudo apt-get install -y mssql-tools

      - name: Test outside SQL connection
        run: sqlcmd -S "${{ env.DB_HOST }}" -U sa -P "${{ env.DB_PASSWORD }}" -d master -Q "SELECT name FROM sys.databases;"
