name: "~ Deploy backend"

on:
  workflow_call:
    inputs:
      dry-run:
        required: false
        default: true
        type: boolean
      artifact:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      SSH_HOST:
        required: true
      SSH_USER:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.5.1
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Download artifacts
        id: download
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact }}

      - name: Deploy to production with rsync (dry-run)
        if: inputs.dry-run && inputs.environment == 'production'
        run: rsync -avhzn ${{steps.download.outputs.download-path}} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/opt/mikane/server/ --delete

      - name: Deploy to production with rsync
        if: ${{!inputs.dry-run && inputs.environment == 'production'}}
        run: |
          rsync -avhz ${{steps.download.outputs.download-path}} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/opt/mikane/server/ --delete

      - name: Reload backend production
        if: ${{!inputs.dry-run && inputs.environment == 'production'}}
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export PATH="$PATH:/home/${{ secrets.SSH_USER }}/.nvm/versions/node/v18.19.0/bin/"
            cd /opt/mikane/server/
            npm install swagger-ui-express --prefix mikane
            cp .env ./mikane/.env
            pm2 reload ecosystem.config.js

      - name: Deploy to staging with rsync (dry-run)
        if: inputs.dry-run && inputs.environment == 'staging'
        run: rsync -avhzn ${{steps.download.outputs.download-path}} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/opt/mikane-staging/ --delete

      - name: Deploy to staging with rsync
        if: ${{!inputs.dry-run && inputs.environment == 'staging'}}
        run: |
          rsync -avhz ${{steps.download.outputs.download-path}} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/opt/mikane-staging/ --delete

      - name: Deploy to test with rsync (dry-run)
        if: inputs.dry-run && inputs.environment == 'test'
        run: rsync -avhzn ${{steps.download.outputs.download-path}} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/opt/mikane-test/ --delete

      - name: Deploy to test with rsync
        if: ${{!inputs.dry-run && inputs.environment == 'test'}}
        run: |
          rsync -avhz ${{steps.download.outputs.download-path}} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/opt/mikane-test/ --delete

      - name: Reload backend test
        if: ${{!inputs.dry-run && inputs.environment == 'test'}}
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export PATH="$PATH:/home/${{ secrets.SSH_USER }}/.nvm/versions/node/v18.19.0/bin/"
            cd /opt/mikane-test/
            npm install swagger-ui-express --prefix mikane
            cp .env ./mikane/.env
            pm2 reload ecosystem.config.js
