name: backend

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build-backend:
    uses: ./.github/workflows/backend-build.yml
    with:
      node-version: 20.x
      upload-artifact: true
  test-backend:
    uses: ./.github/workflows/backend-test.yml
    with:
      node-version: 20.x
  deploy-backend:
    if: github.event_name == 'push'
    needs: [build-backend, test-backend]
    uses: ./.github/workflows/backend-deploy.yml
    with:
      dry-run: false
      environment: test
      artifact: ${{ needs.build-backend.outputs.artifact }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
