name: "~ Bump version"
on:
  workflow_call:
    inputs:
      bump:
        required: true
        type: string
      node-version:
        required: true
        type: string
      dry-run:
        required: true
        default: false
        type: boolean
    secrets:
      commit-key:
        required: true
    outputs:
      tag:
        description: "The git tag"
        value: ${{ jobs.bump.outputs.tag}}
jobs:
  bump:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.summary.outputs.version_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.commit-key }}

      - name: Setup Node ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Bump frontend version
        id: bump-frontend
        run: |
          cd ./app/mikane/
          echo "NEW_VERSION=$(npm --no-git-tag-version version $VERSION)" >> $GITHUB_ENV
        env:
          VERSION: ${{ inputs.bump }}

      - name: Bump backend version
        id: bump-backend
        run: |
          cd ./server/
          npm --no-git-tag-version version $VERSION
        env:
          VERSION: ${{ inputs.bump }}

      - name: Commit package.json changes and create tag
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git add "./app/mikane/package.json"
          git add "./server/package.json"
          git commit -m "chore: release ${{ env.NEW_VERSION }}"
          git tag ${{ env.NEW_VERSION }}

      - name: Push changes to repository
        if: ${{ !inputs.dry-run }}
        run: |
          git push origin ${{ github.ref_name }}
          git push origin tag ${{ env.NEW_VERSION }}

      - name: Summary
        id: summary
        run: |
          echo "version_tag=${{ env.NEW_VERSION }}" >> $GITHUB_OUTPUT
          echo Bumped and tagged version ${{ env.NEW_VERSION }} >> $GITHUB_STEP_SUMMARY
