name: Build and deploy frontend release
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Full version number to build and deploy
        type: string
      node-version:
        required: true
        default: 20.x
        description: Node version to use
        type: choice
        options:
          - 20.x
          - 18.x
      upload-coverage:
        required: false
        default: true
        description: Upload code coverage
        type: boolean
      environment:
        required: true
        default: test
        description: Environment to deploy to
        type: choice
        options:
          - staging
          - production
          - test
      dry-run:
        required: false
        default: false
        description: Dry run for testing
        type: boolean

jobs:
  bump:
    uses: ./.github/workflows/frontend-bump.yml
    with:
      version: ${{ inputs.version }}
      node-version: ${{ inputs.node-version }}
      dry-run: ${{ inputs.dry-run }}
    secrets:
      github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  test:
    needs: bump
    uses: ./.github/workflows/frontend-test.yml
    with:
      node-version: ${{ inputs.node-version }}
      upload-coverage: ${{ inputs.upload-coverage }}
  build:
    needs: bump
    uses: ./.github/workflows/frontend-build.yml
    with:
      tag: v${{ inputs.version }}
      node-version: ${{ inputs.node-version }}
      upload-artifact: true
      environment: ${{ inputs.environment }}
      dry-run: ${{ inputs.dry-run }}
  deploy:
    needs: [build, test]
    uses: ./.github/workflows/frontend-deploy.yml
    with:
      dry-run: ${{ inputs.dry-run }}
      artifact: ${{ needs.build.outputs.artifact }}
      environment: ${{ inputs.environment }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
