name: frontend

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build-frontend:
    uses: ./.github/workflows/frontend-build.yml
    with:
      node-version: 18.x
  test-frontend:
    uses: ./.github/workflows/frontend-test.yml
    with:
      node-version: 18.x
  deploy-frontend:
    if: github.event_name == 'push'
    needs: [build-frontend, test-frontend]
    uses: ./.github/workflows/backend-deploy.yml
    with:
      dry-run: false
      environment: test
      artifact: ${{ needs.build-frontend.outputs.artifact }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
