name: frontend

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build-frontend:
    uses: ./.github/workflows/frontend-build.yml
    with:
      node-version: 18.x
  test-frontend:
    uses: ./.github/workflows/frontend-test.yml
    with:
      node-version: 18.x
