name: "~ Frontend tests"
on:
  workflow_call:
    inputs:
      upload-coverage:
        required: false
        default: true
        description: Upload code coverage
        type: boolean
      node-version:
        required: true
        default: 20.x
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/mikane/
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: "npm"
          cache-dependency-path: ./app/mikane/package-lock.json
      - run: npm ci --include=optional
      - run: npm test
      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        if: inputs.upload-coverage
        with:
          files: ./app/mikane/coverage/mikane/cobertura-coverage.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
