name: Build and deploy frontend release
on:
    workflow_dispatch:
        inputs:
            version:
                required: true
                description: Full version number to build and deploy
                type: string
            node-version:
                required: true
                default: 16.x
                description: Node version to use
                type: choice
                options:
                    - 20.x
                    - 18.x
                    - 16.x
            upload-coverage:
                required: false
                default: true
                description: Upload code coverage
                type: boolean
            environment:
                required: true
                default: staging
                description: Environment to deploy to
                type: choice
                options:
                    - staging
                    - production
            dry-run:
                required: false
                default: false
                description: Dry run for testing
                type: boolean

jobs:
    bump:
        uses: ./.github/workflows/frontend-bump.yml
        with:
            version: ${{ inputs.version }}
            node-version: ${{ inputs.node-version }}
            dry-run: ${{ inputs.dry-run }}
        secrets:
            github-token: ${{ secrets.GITHUB_TOKEN }}
    test:
        needs: bump
        uses: ./.github/workflows/frontend-test.yml
        with:
            node-version: ${{ inputs.node-version }}
            upload-coverage: ${{ inputs.upload-coverage }}
    build:
        needs: bump
        uses: ./.github/workflows/frontend-build.yml
        with:
            tag: v${{ inputs.version }}
            node-version: ${{ inputs.node-version }}
            upload-artifact: true
    deploy:
        needs: [build, test]
        uses: ./.github/workflows/deploy.yml
        with:
            version: ${{ inputs.version }}
            artifact: ${{ needs.build.outputs.artifact }}
            environment: ${{ inputs.environment }}
