name: Bump and deploy release
on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Bump version"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major
      node-version:
        description: "Node version"
        required: true
        type: choice
        default: 22.x
        options:
          - 20.x
          - 22.x
      dry-run:
        description: "Dry run for testing"
        required: false
        default: false
        type: boolean

jobs:
  test-frontend:
    uses: ./.github/workflows/frontend-test.yml
    with:
      node-version: ${{ inputs.node-version }}
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
  test-backend:
    uses: ./.github/workflows/backend-test.yml
    with:
      node-version: ${{ inputs.node-version }}
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
  bump:
    needs: [test-frontend, test-backend]
    uses: ./.github/workflows/bump.yml
    with:
      bump: ${{ inputs.bump }}
      node-version: ${{ inputs.node-version }}
      dry-run: ${{ inputs.dry-run }}
    secrets:
      github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
